
if (APPLE)
  set(_FFTW_PREFIX "/opt/homebrew")
endif()

if(WIN32 )
  set(_FFTW_PREFIX "${PROJECT_SOURCE_DIR}/3rdparty/fftw")
endif()

set(_FFTW_INCLUDE_DIR "${_FFTW_PREFIX}/include")
set(_FFTW_LIBRARY_DIR "${_FFTW_PREFIX}/lib")
set(_FFTW_LIBRARIE_fftw3f "${CMAKE_SHARED_LIBRARY_PREFIX}fftw3f${CMAKE_SHARED_LIBRARY_SUFFIX}")

add_library(FFTW::fftw3f SHARED IMPORTED)
set_target_properties(FFTW::fftw3f PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_FFTW_INCLUDE_DIR}"
  IMPORTED_IMPLIB "${_FFTW_LIBRARY_DIR}/${_FFTW_LIBRARIE_fftw3f}"
)
